
algoritmo "horas extras trabalhadas"

var

horas_extras_trabalhadas : inteiro
valor_hora_extra : real
salario_hora_extra : real

inicio

escreva ("horas extras trabalhadas: ")
leia (horas_extras_trabalhadas)

escreva ("valor hora extra: ")
leia (valor_hora_extra)

salario_hora_extra <- horas_extras_trabalhadas * valor_hora_extra

escreval ()
escreva("salario hora extra: R$",salario_hora_extra)

fimalgoritmo
